services:
  - type: web
    name: taobao-arbitrage-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python main.py
    autoDeploy: false
